---
title: "Google AdWord Correlations"
author: "Curtis L. Hampton"
output: html_notebook
---

```{r}
library(corrplot)
```

```{r}
# read CSV file into a dataframe
ads <- read.csv("adwords_clean_31oct2015_31oct2016.csv", stringsAsFactors = FALSE)
```

```{r}
# inspect the sturcture of the dataset
str(ads)
```

```{r}
# drop non-relevant columns
ads$full_description <- NULL
ads$description <- NULL
ads$ad_group <- NULL
ads$description_line_2 <- NULL
ads$description_line_1 <- NULL
ads$ad_id <- NULL
ads$description.words <- NULL
ads$ad_state <- NULL
ads$clean_words <- NULL
```

```{r}
# summarize relevant metric data data
lapply(list(ads$conv_rate, ads$bounce_rate, ads$CTR, ads$description_length), FUN=summary)
```

```{r}
# sort the dataframe by conversion rate
ads <- ads[order(-ads$conv_rate), ]
```

```{r}
# show the first 5 observations
head(ads)
```

```{r}
# show the bivariate correlation matrix
m <- cor(ads)
corrplot(m, method="shade", type="upper", diag=FALSE)
```

```{r}
# correlate CTR with all other variables
barplot(cor(ads$CTR, as.matrix(ads[sapply(ads, is.numeric)])), las=2, main="Click Through Rate (CTR) Correlations")
```

```{r}
# correlate Bounce Rate with all other variables
barplot(cor(ads$bounce_rate, as.matrix(ads[sapply(ads, is.numeric)])), las=2, main="Bounce Rate Correlations")
```

```{r}
# correlate Conversion Rate with all other variables
barplot(cor(ads$conv_rate, as.matrix(ads[sapply(ads, is.numeric)])), las=2, main="Conversion Rate Correlations")
```