---
title: "Temperature during Total Solar Eclipse 2017"
author: "Curtis L. Hampton"
date: "August 21, 2017"
output: html_notebook
---

```{r message=FALSE}
library(RPostgreSQL)
library(reshape2)
library(ggplot2)
```

```{r results='hide'}
# connect to the database
con <- dbConnect(dbDriver("PostgreSQL"), 
                 dbname = "postgres",
                 host = "localhost", 
                 port = 5432,
                 user = "postgres", 
                 password = "apassword")
```

```{r}
# get the weather for Arlington
query1 = "SELECT datetime, 
          weather -> 'current_observation' ->> 'temp_f' AS outside_temp
          FROM arlington_weather
          WHERE date_trunc('day', datetime) = '2017-08-21'
          ORDER BY datetime
         "

# store query results in a dataframe 
df_mon <- dbGetQuery(con, query1)
```

```{r}
# get the weather for Arlington
query2 = "SELECT datetime, 
          weather -> 'current_observation' ->> 'temp_f' AS outside_temp
          FROM arlington_weather
          WHERE date_trunc('day', datetime) = '2017-08-20'
          ORDER BY datetime
         "

# store query results in a dataframe 
df_tue <- dbGetQuery(con, query2)
```

```{r}
# disconnect from the database
dbDisconnect(con)
```

```{r}
# store temp_f as float
df_mon$outside_temp <- as.numeric(df_mon$outside_temp)
df_tue$outside_temp <- as.numeric(df_tue$outside_temp)
```

```{r}
# plot temperatures over time on the day before the eclipse
p1 <-ggplot(data=df_tue, aes(x=datetime, y=outside_temp)) +
     geom_line(aes(color=outside_temp)) +
     geom_point(size=1.5, aes(color=outside_temp)) +
     scale_color_gradient2(midpoint=median(df_tue$outside_temp), low="blue", mid="white", high="red" ) +
     scale_y_continuous(breaks = round(seq(min(df_tue$outside_temp), max(df_tue$outside_temp), by = 2.0),1),
                        ylab("")) +
     ggtitle('Arlington, VA Temperature on August 20st, 2017') +
     theme(plot.title=element_text(lineheight=.8, face="bold", hjust=0.5),
           legend.position='none',
           panel.background = element_rect(fill = 'black', colour = 'black'),
           panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            axis.title.x=element_blank())

```

```{r}
# show the plot
p1
```

```{r}
# plot temperatures over time on the day of the eclipse
p2 <- ggplot(data=df_mon, aes(x=datetime, y=outside_temp)) +
      geom_line(aes(color=outside_temp)) +
      geom_point(size=1.5, aes(color=outside_temp)) +
      scale_color_gradient2(midpoint=median(df_mon$outside_temp), low="blue", mid="white", high="red" ) +
      scale_y_continuous(breaks = round(seq(min(df_mon$outside_temp), max(df_mon$outside_temp), by = 2.0),1),
                         ylab("")) +
      ggtitle('Arlington, VA Temperature on August 21st, 2017') +
      theme(plot.title=element_text(lineheight=.8, face="bold", hjust=0.5),
            legend.position='none',
            panel.background = element_rect(fill = 'black', colour = 'black'),
            panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            axis.title.x=element_blank())
```

```{r}
p2
```