---
title: "Hows the weather out there?"
author: "Curtis L. Hampton"
output: html_notebook
---

```{r message=FALSE}
library(RPostgreSQL)
library(reshape2)
library(ggplot2)
```

```{r results='hide'}
# connect to the database
con <- dbConnect(dbDriver("PostgreSQL"), 
                 dbname = "postgres",
                 host = "localhost", 
                 port = 5432,
                 user = "postgres", 
                 password = "apassword")
```

```{r}
# get the weather for Arlington
query = "SELECT datetime, 
                (condition -> 'current_observation' ->> 'temp_f')::numeric as temp_f,
                (condition -> 'current_observation' ->> 'weather')::text as weather,
                (condition -> 'current_observation' ->> 'wind_dir')::text as wind_dir,
                (condition -> 'current_observation' ->> 'wind_mph')::numeric as wind_mph,
                (condition -> 'current_observation' ->> 'dewpoint_f')::numeric as dewpoint_f,
                (condition -> 'current_observation' ->> 'feelslike_f')::numeric as feelslike_f,
                (condition -> 'current_observation' ->> 'pressure_in')::numeric as pressure_in,
                (condition -> 'current_observation' ->> 'wind_string')::text as wind_string,
                (condition -> 'current_observation' ->> 'windchill_f')::text as windchill_f,
                (condition -> 'current_observation' ->> 'visibility_mi')::numeric as visibility_mi,
                (condition -> 'current_observation' ->> 'wind_gust_mph')::numeric as wind_gust_mpg,
                (condition -> 'current_observation' ->> 'solarradiation')::numeric as solarradiation,
                (condition -> 'current_observation' ->> 'relative_humidity')::text as relative_humidity
         FROM arlington_weather_condition
        "

# store query results in a dataframe 
df <- dbGetQuery(con, query)

# disconnect from the database
dbDisconnect(con)
```

```{r}
# show the first 5 observations
head(df)
```

```{r}
# convert weather to a factor
df$weather <- factor(df$weather, levels=c("Clear", "Overcast", "Partly Cloudy", "Mostly Cloudy", "Light Rain", "Rain"), ordered=FALSE)
```

```{r}
# convert humidity to a numeric
df$relative_humidity <- as.numeric(sub("%","",df$relative_humidity))/100
```

```{r}
# check the structure of the data
str(df)
```

```{r}
# plot temperatures over time
ggplot(data=df, aes(x=datetime, y=temp_f)) +
  geom_line(size=1.0) +
  geom_point(size=2.0) +
  ggtitle('Temperature')
```

```{r}
# plot the number of records by weather condition
ggplot(data = df, mapping = aes(x = weather)) +
  geom_bar(aes(fill = weather)) +
  ggtitle("Weather conditions")
```

```{r}
# plot humidity over time
ggplot(data=df, aes(x=datetime, y=relative_humidity)) +
  geom_line(size=1.0) +
  geom_point(size=1.5) +
  ggtitle("Relative Humidity")
```

```{r}
# plot visibility over time
ggplot(data=df, aes(x=datetime, y=visibility_mi)) +
  geom_line() +
  geom_point() +
  ggtitle("Visibility")
```
