---
title: "Predicting the Temperature"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r echo=FALSE, message=FALSE}
library(RPostgreSQL)
library(plyr)
library(lubridate)
library(ggplot2)
library(corrplot)
```

```{r echo=FALSE, message=FALSE, results='hide'}
# connect to the database
con <- dbConnect(dbDriver("PostgreSQL"), 
                 dbname = "postgres",
                 host = "localhost", 
                 port = 5432,
                 user = "postgres", 
                 password = "apassword")
```

```{r, echo=FALSE, message=FALSE}
# get the weather for Arlington
query1 = "SELECT * FROM arlington_weather_condition_2018"

# store query results in a dataframe 
df <- dbGetQuery(con, query1)
```

```{r echo=FALSE, results=FALSE}
# inspect the data types
str(df)

# rename observation_epoch to datetime
df <- rename(df, c(observation_epoch="datetime"))

# drop non-complete case data
df <- na.omit(df)
```

```{r}
# look at the data
head(df)
```

```{r fig.align="center"}
# plot boxplot to understand how temperature variables by weather
ggplot(data = df, mapping = aes(x = weather, y = temp_f, color = weather)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "none")
```


```{r fig.align="center"}
# look at correlations between variables
df.num <- df[, sapply(df, is.numeric)]
df.num.M = cor(df.num)
corrplot(df.num.M, 
         type = "upper", 
         method = "number", 
         number.cex = 0.7, 
         tl.cex = 0.7, 
         tl.col = "black")
```

```{r}
# fit a multiple linear regression to predict temp_f
fit <- lm(temp_f ~ . -weather -feelslike_f,
          data = df)

# inspect the fit
summary(fit)
```

```{r fig.align="center"}
# evaluate assumptions
plot(fit)
```