---
title: "Predicting the Temperature"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

```{r echo=FALSE, message=FALSE}
library(RPostgreSQL)
library(lubridate)
library(reshape)
library(ggplot2)
library(corrplot)
```

```{r echo=FALSE, message=FALSE, results='hide'}
# connect to the database
con <- dbConnect(dbDriver("PostgreSQL"), 
                 dbname = "postgres",
                 host = "localhost", 
                 port = 5432,
                 user = "postgres", 
                 password = "apassword")
```

```{r, echo=FALSE, message=FALSE}
# get the weather for Arlington
query1 = "SELECT * FROM arlington_weather_condition_2018"

# store query results in a dataframe 
df <- dbGetQuery(con, query1)

# disconnect from the database
dbDisconnect(con)
```

```{r echo=FALSE, results=FALSE}
# inspect the data types
str(df)

# drop non-complete case data
df <- na.omit(df)
```

# Data

```{r echo=TRUE}
# look at the data
tail(df)
```

# Inspection

How does the actual temperature compare to what it "feels like"?

```{r echo=FALSE, fig.align="center", message = FALSE, warning = FALSE}
# reshape dataframe from wide to long
df.temps <- df[c("temp_f", "feelslike_f", "datetime")]
df.temps.long <- melt(df.temps, id=c("datetime"))

# plot actual vs feeslikes temperatures
ggplot(data = df.temps.long, mapping = aes(x = datetime, y = value, color = variable)) +
  geom_line()
```

How does temperature vary by weather condition?

```{r echo=FALSE, fig.align="center", message = FALSE, warning = FALSE}
# plot boxplot to understand how temperature variables by weather
ggplot(data = df, mapping = aes(x = weather, y = temp_f, color = weather)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "none")
```

How correlated are the variables to one another?  How correlated is each variable to the temperature?

```{r echo=FALSE, fig.align="center", message = FALSE, warning = FALSE}
# look at correlations between variables
df.num <- df[, sapply(df, is.numeric)]
df.num.M = cor(df.num)
corrplot(df.num.M, 
         type = "upper", 
         method = "number", 
         number.cex = 0.7, 
         tl.cex = 0.7, 
         tl.col = "black")
```

# Regression

Predicting temperature using all variables except for "feelslike_f"

```{r}
# fit a multiple linear regression to predict temp_f
fit <- lm(temp_f ~ . -feelslike_f,
          data = df)

# inspect the fit
summary(fit)
```

# Evaluate Model Fit

```{r echo=FALSE, fig.align="center", message = FALSE, warning = FALSE}
# evaluate assumptions
plot(fit)
```

```{r}
# look for observations with high leverage
cutoff <- 4/((nrow(df)-length(fit$coefficients)-2))
plot(fit, which=4, cook.levels=cutoff)
```

```{r}
# join the results with original data
results <- cbind(pred = predict(fit), resid = resid(fit), std_resid = rstandard(fit), df)

# sort the results by residual value
results <- results[order(results$resid), ]

# inspect outliers
head(results)

```

```{r}
# plot residual by weather condition
ggplot(data = results) +
  geom_boxplot(mapping = aes(x = weather, y = std_resid, fill = weather)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "none")
```

