---
title: "R Notebook"
output: html_notebook
---

```{r}
library('igraph')
```

```{r}
nodes <- read.csv("Calibration-NODES.csv", header=T, as.is=T)
links <- read.csv("Clibration-EDGES.csv", header=T, as.is=T)
```

```{r}
links <- aggregate(links[,3], links[,-3], sum)
links <- links[order(links$from, links$to),]
colnames(links)[3] <- "weight"
rownames(links) <- NULL
```

```{r}
net <- graph_from_data_frame(d=links, vertices=nodes, directed=T) 
net
```
```{r}
#E(net)$highlight <- c(1,1,1,1,0,1,1,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1)
E(net)$highlight <- c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1)
E(net)$color <- ifelse(E(net)$highlight == 1, "gray", "red")
```

```{r}
par(bg=NA)
plot(net, 
     layout=layout_on_grid(net, dim=3), 
     edge.arrow.size=.75, 
     edge.width=links$weight,
     edge.label=links$weight, 
     edge.label.color='black',
     edge.label.cex=0.75,
     edge.curved=.3,
     vertex.color='gray',
     vertex.size=20,
     vertex.label.color='black'
)

dev.copy(png,'myplot.png', width=6, height=6, units="in",res=500)
dev.off()
```
```{r}

```

